### ISSUE TITLE
what is the number format for --postage

### ISSUE THREAD

**Issue by xspoco** [gmart7t2/ord#2]
hi, i use --postage  set amount in the inscription
but it reported an error

> `ord52 --bitcoin-data-dir "D:\Bitcoin\blocks" --cookie-file "D:\Bitcoin\.cookie" --wallet ord2 wallet inscribe --fee-rate 5 --postage 546 "C:\Users\Administrator\Desktop\N.txt"`
> error: Invalid value "546" for '--postage <POSTAGE>': invalid number format
> 
> For more information try --help

![image](https://user-images.githubusercontent.com/19290455/234851872-dac1205b-27f9-441a-8c10-021d8d7c4962.png)

**Comment by xspoco** [comment]
and --csv

> `ord52 --bitcoin-data-dir "D:\Bitcoin\blocks" --cookie-file "D:\Bitcoin\.cookie" --wallet ord2 wallet inscribe --fee-rate 5 --csv "C:\Users\Administrator\Desktop\1.csv"`
> error: base58 address encoding error
> because: length 47 invalid for this base58 type

![image](https://user-images.githubusercontent.com/19290455/234721356-860231ac-b675-4c07-8abf-f488d319e6b7.png)

Is my usage correct?

**Comment by huguojunsy** [comment]
The some question.
